'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Lock, Home, ArrowLeft, CheckCircle, Clock, Link as LinkIcon, Database, Server } from 'lucide-react';

interface RawAlert {
  id: string;
  type: string;
  zone: string;
  msg?: string;
  timestamp: string;
  hash?: string;
  previous_hash?: string;
}

export default function BlockchainPage() {
  const [alerts, setAlerts] = useState<RawAlert[]>([]);
  const router = useRouter();
  const baseUrl = process.env.NEXT_PUBLIC_PYTHON_SERVER_URL || 'http://localhost:8000';

  useEffect(() => {
    const fetchAnalytics = async () => {
      try {
        const response = await fetch(`${baseUrl}/analytics/global`);
        if (response.ok) {
          const data = await response.json();
          setAlerts(data.recent_alerts || []);
        }
      } catch (err) {
        console.error('Failed to fetch analytics:', err);
      }
    };
    
    fetchAnalytics();
    const interval = setInterval(fetchAnalytics, 2000);
    return () => clearInterval(interval);
  }, [baseUrl]);

  return (
    <div className="min-h-screen bg-brand-bg text-brand-text font-mono flex flex-col">
      {/* Header */}
      <header className="border-b border-brand-border/50 bg-black/80 px-6 py-4 flex items-center justify-between sticky top-0 z-10 backdrop-blur">
        <div className="flex items-center gap-4">
          <button onClick={() => router.push('/dashboard')} className="p-2 hover:bg-brand-card/20 rounded-lg text-brand-muted transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="text-xl font-bold tracking-widest text-brand-red flex items-center gap-2">
              <Lock className="w-5 h-5" />
              IMMUTABLE AUDIT LEDGER
            </h1>
            <p className="text-xs text-brand-muted/70 tracking-widest uppercase mt-1">Cryptographic Hash Verification // SHA-256</p>
          </div>
        </div>
        <div className="flex items-center gap-6 text-xs font-bold tracking-widest text-brand-muted">
          <div className="flex items-center gap-2"><Server className="w-4 h-4" /> NODE: ACTIVE</div>
          <div className="flex items-center gap-2"><Database className="w-4 h-4" /> BLOCKS: {alerts.length}</div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 p-6 md:p-10 max-w-6xl mx-auto w-full">
        
        <div className="mb-8 border border-brand-border/40 bg-brand-card/10 p-5 rounded-lg flex items-start gap-4">
          <Lock className="w-8 h-8 text-brand-red shrink-0 mt-1" />
          <div>
            <h2 className="text-lg font-bold text-brand-text mb-2 tracking-wider">CRYPTOGRAPHIC INTEGRITY ACTIVE</h2>
            <p className="text-sm text-brand-text/70 leading-relaxed max-w-3xl">
              All tactical alerts generated by the Edge AI are cryptographically hashed using SHA-256. 
              Each block contains the hash of the previous event, forming an immutable chain. 
              Any attempt to delete, alter, or falsify surveillance logs will instantly break the cryptographic chain, ensuring 100% accountability.
            </p>
          </div>
        </div>

        <div className="space-y-6">
          {alerts.slice().reverse().map((alert, idx) => (
            <div key={idx} className="relative pl-8 md:pl-0">
              
              {/* Timeline Connector */}
              {idx !== alerts.length - 1 && (
                <div className="absolute left-[15px] md:left-[39px] top-10 bottom-[-24px] w-px bg-brand-card/50"></div>
              )}
              
              <div className="border border-brand-border/40 bg-brand-card p-5 rounded-lg md:ml-20 relative hover:border-brand-red/30 transition-colors shadow-[0_0_15px_rgba(0,0,0,0.5)]">
                
                {/* Timeline Node */}
                <div className="absolute left-[-29px] md:left-[-60px] top-5 w-8 h-8 rounded-full bg-brand-card/20 border border-brand-red flex items-center justify-center shadow-[0_0_10px_rgba(239,51,72,0.3)]">
                  <CheckCircle className="w-4 h-4 text-brand-text" />
                </div>
                
                <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                        alert.type === 'overcrowding' ? 'bg-amber-900/40 text-amber-400' :
                        alert.type === 'no_entry_violation' ? 'bg-red-900/40 text-red-400' :
                        'bg-brand-card/40 text-brand-text'
                      }`}>
                        {alert.type.replace('_', ' ')}
                      </span>
                      <span className="text-xs text-brand-red/70 flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {new Date(alert.timestamp).toLocaleString()}
                      </span>
                    </div>
                    
                    <h3 className="text-base font-bold text-brand-text mb-1">{alert.zone}</h3>
                    <p className="text-sm text-brand-text/50">{alert.msg || 'System generated event log.'}</p>
                  </div>
                  
                  <div className="bg-black/50 p-3 rounded border border-brand-border/30 md:w-[450px] shrink-0 font-mono text-[10px] space-y-2">
                    <div>
                      <span className="text-brand-muted/70 block mb-0.5 flex items-center gap-1">
                        <LinkIcon className="w-3 h-3" /> PREVIOUS HASH
                      </span>
                      <span className="text-gray-400 break-all">{alert.previous_hash || '0000000000000000000000000000000000000000000000000000000000000000'}</span>
                    </div>
                    <div>
                      <span className="text-brand-muted/70 block mb-0.5 flex items-center gap-1">
                        <Lock className="w-3 h-3" /> BLOCK HASH (SHA-256)
                      </span>
                      <span className="text-brand-text font-bold break-all">{alert.hash || 'pending...'}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
          
          {alerts.length === 0 && (
            <div className="text-center py-20 border border-dashed border-brand-border/40 rounded-lg">
              <Database className="w-8 h-8 text-brand-muted mx-auto mb-3" />
              <p className="text-brand-red/70">No blocks have been generated yet.</p>
            </div>
          )}
          
          {alerts.length > 0 && (
            <div className="relative pl-8 md:pl-0">
              <div className="md:ml-20 flex items-center gap-3 text-brand-muted/50 text-xs py-4">
                <div className="w-2 h-2 rounded-full bg-brand-card"></div>
                GENESIS BLOCK REACHED
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}


