'use client';

import { useRouter } from 'next/navigation';
import { ArrowRight, Crosshair, Radio, ScanLine, ShieldAlert } from 'lucide-react';
import Logo from '@/components/Logo';

export default function LandingPage() {
  const router = useRouter();
  return (
    <main className="min-h-screen overflow-hidden bg-[#06070c] text-[#e4f3f5]">
      <nav className="relative z-20 flex items-center justify-between border-b border-cyan-300/20 bg-black/80 px-5 py-3 backdrop-blur md:px-10">
        <Logo size="md" />
        <div className="hidden gap-8 text-[11px] font-bold tracking-[.16em] text-cyan-100/70 md:flex"><a href="#overview" className="hover:text-[#ff6268]">OVERVIEW</a><a href="#network" className="hover:text-[#ff6268]">NETWORK</a><a href="/tour" className="text-[#ff777c]">GUIDED TOUR</a></div>
        <button onClick={() => router.push('/tour')} className="border border-[#ff5258] bg-[#ff5258]/10 px-4 py-2 text-[11px] font-bold tracking-widest text-[#ff9094] hover:bg-[#ff5258] hover:text-[#19090a]">LAUNCH PROTOTYPE</button>
      </nav>

      <section id="overview" className="relative min-h-[calc(100vh-65px)] overflow-hidden px-5 py-10 md:px-10 md:py-14">
        <div className="absolute inset-0 opacity-35 [background-image:linear-gradient(rgba(107,220,238,.14)_1px,transparent_1px),linear-gradient(90deg,rgba(107,220,238,.14)_1px,transparent_1px)] [background-size:54px_54px]" />
        <div className="absolute left-0 top-[46%] h-px w-full bg-[#ff4e55]/70 shadow-[0_0_20px_#ff3038]" />
        <div className="absolute -right-30 top-[-20%] h-[850px] w-[850px] rounded-full border border-cyan-300/20 bg-[radial-gradient(circle_at_45%_45%,rgba(90,190,216,.24),rgba(15,25,42,.05)_44%,transparent_66%)]" />
        <div className="absolute right-[14%] top-[14%] h-110 w-110 rounded-full border border-cyan-200/35 opacity-80"><div className="absolute inset-8 rounded-full border border-dashed border-cyan-100/30" /><div className="absolute left-1/2 top-0 h-1/2 w-px origin-bottom rotate-[62deg] bg-[#ff5c63] shadow-[0_0_12px_#ff5c63]" /></div>
        <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.86fr_1.14fr]">
          <div className="z-10"><p className="tactical-kicker mb-5">TRINETRA // INTEGRATED BORDER OPERATIONS</p><h1 className="max-w-xl text-5xl font-bold leading-[.94] tracking-tight md:text-7xl">A shared picture.<br /><span className="text-[#ff6168]">A faster response.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-cyan-50/65">TRINETRA brings video, thermal, radar and field assets into one operational view—so commanders can recognize, verify and coordinate a response without switching systems.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => router.push('/tour')} className="flex items-center gap-2 bg-[#ff5258] px-5 py-3 text-xs font-bold tracking-wider text-[#18090a] hover:bg-[#ff797d]">TAKE THE GUIDED TOUR <ArrowRight className="h-4 w-4" /></button><button onClick={() => document.getElementById('network')?.scrollIntoView({ behavior: 'smooth' })} className="border border-cyan-200/40 px-5 py-3 text-xs font-bold tracking-wider text-cyan-100 hover:border-[#ff5258]">EXPLORE THE SYSTEM</button></div><div className="mt-12 grid max-w-md grid-cols-3 gap-5 border-t border-cyan-200/25 pt-5"><div><b className="text-xl text-[#8ee8f4]">04</b><p className="mt-1 text-[9px] tracking-widest text-cyan-50/55">LIVE LAYERS</p></div><div><b className="text-xl text-[#8ee8f4]">12ms</b><p className="mt-1 text-[9px] tracking-widest text-cyan-50/55">SIGNAL DELAY</p></div><div><b className="text-xl text-[#ff858a]">P2</b><p className="mt-1 text-[9px] tracking-widest text-cyan-50/55">ACTIVE EVENT</p></div></div></div>
          <div className="relative min-h-[430px] border border-cyan-200/30 bg-[#0b101a]/75 p-3 shadow-[0_0_70px_rgba(26,163,187,.12)] backdrop-blur"><div className="flex justify-between border-b border-cyan-200/20 px-2 pb-3 text-[10px] font-bold tracking-widest text-cyan-100/65"><span>SECTOR VIEW // NORTH RIDGE</span><span className="text-[#ff777c]">● PRIORITY WATCH</span></div><div className="relative mt-3 h-[370px] overflow-hidden bg-[radial-gradient(ellipse_at_70%_40%,rgba(33,84,105,.7),transparent_27%),radial-gradient(ellipse_at_22%_82%,rgba(60,87,57,.6),transparent_26%),linear-gradient(140deg,#151c2a,#111a22_47%,#213229_48%,#0b0f15)]"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(rgba(122,224,238,.16)_1px,transparent_1px),linear-gradient(90deg,rgba(122,224,238,.16)_1px,transparent_1px)] [background-size:38px_38px]" /><div className="absolute left-[49%] top-[43%] h-28 w-28 rounded-full border border-dashed border-cyan-100/55"><div className="absolute inset-3 rounded-full border border-cyan-100/35" /><div className="absolute left-1/2 top-1/2 h-px w-30 origin-left -rotate-25 bg-[#ff555c] shadow-[0_0_13px_#ff555c]" /></div><div className="absolute left-[50%] top-[45%] h-7 w-7 rounded-full border-2 border-[#ff5b62] bg-[#361215]/80 p-1 text-[#ff8d91] shadow-[0_0_20px_#ff4d54]"><Crosshair className="h-4 w-4" /></div><p className="absolute left-[56%] top-[43%] text-[10px] font-bold tracking-widest text-[#ffc1c3]">TRACK 042<br /><span className="font-normal text-cyan-100/70">CONFIDENCE 87%</span></p><div className="absolute bottom-5 left-5 flex items-center gap-2 text-[10px] tracking-widest text-cyan-100"><Radio className="h-4 w-4 text-[#7be1ef]" /> RADAR-02: LINKED</div><div className="absolute bottom-5 right-5 flex items-center gap-2 text-[10px] tracking-widest text-cyan-100"><ScanLine className="h-4 w-4 text-[#7be1ef]" /> THERMAL-04: ACTIVE</div></div></div>
        </div>
      </section>
      <section id="network" className="relative border-y border-cyan-200/20 bg-[#0a0d14] px-5 py-14 md:px-10"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[.8fr_1.2fr]"><div><p className="tactical-kicker">Mission architecture</p><h2 className="mt-4 text-3xl font-bold">Designed for the decisions that cannot wait.</h2></div><div className="grid gap-px border border-cyan-200/20 bg-cyan-200/20 sm:grid-cols-3">{[[ShieldAlert, 'DETECT', 'Correlate unusual activity across sensors.'], [ScanLine, 'VERIFY', 'Inspect confidence and live evidence.'], [Radio, 'COORDINATE', 'Task assets and preserve the audit trail.']].map(([Icon, title, text]) => { const ItemIcon = Icon as typeof ShieldAlert; return <div key={title as string} className="bg-[#0a0d14] p-5"><ItemIcon className="h-5 w-5 text-[#ff646a]" /><p className="mt-7 text-sm font-bold tracking-widest">{title as string}</p><p className="mt-2 text-xs leading-5 text-cyan-50/55">{text as string}</p></div>; })}</div></div></section>
    </main>
  );
}
